name: 'Repository Maintainance'

on:
  workflow_dispatch:
  schedule:
    - cron: '49 8 * * 5'

jobs:
  action:
    name: 'Repository Maintenance'
    uses: mprins/.github/.github/workflows/maintenance.yml@main
    with:
        issue-inactive-days: '90'
        pr-inactive-days: '60'
